# Metadata
site_name: REST Against Humanity
site_url: https://restagainsthumanity.com
site_author: celsius narhwal

# Repository
repo_name: celsiusnarhwal/rest-against-humanity
repo_url: https://github.com/celsiusnarhwal/rest-against-humanity

# Material for MkDocs
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: light-mode
        name: Step into the light

    - media: "(prefers-color-scheme: light)"
      scheme: indigo
      primary: white
      toggle:
        icon: dark-mode
        name: Embrace the dark
  font:
    text: Roboto
    code: Roboto Mono
  favicon: fontawesome/solid/cards-blank
  icon:
    logo: fontawesome/solid/cards-blank
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/notes
      tip: material/lightbulb-on
      danger: material/fire

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - typeset
  - iconoclast:
      css: true
      kit:
        name: General
  - iconocards

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - docs/.overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: celsiusnarhwal
      repo: 3515.games
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

# Additional Settings
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/celsiusnarhwal
      name: github.com/celsiusnarhwal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/celsiusnarhwal
      name: "@celsiusnarhwal"
    - icon: fontawesome/solid/envelope
      link: mailto:hello@celsiusnarhwal.dev
    - icon: celsius
      link: https://celsiusnarhwal.dev
      name: celsiusnarhwal.dev
  generator: false

# CSS
extra_css:
  - assets/stylesheets/admonitions.css
  - assets/stylesheets/extra.css

# JavaScript
extra_javascript:
  - "https://kit.fontawesome.com/2273b2767b.js"
