[tool.poetry]
name = "rest-against-humanity"
version = "0.1.0"
description = ""
authors = ["celsius narhwal <70828899+celsiusnarhwal@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
