[tool.poetry]
name = "rest-against-humanity"
version = "2.0.0"
description = "A public API for Cards Against Humanity"
authors = ["celsius narhwal <celsiusnarhwal@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.92.0"
ujson = "^5.7.0"

[tool.poetry.group.dev.dependencies]
pyperclip = "^1.8.2"
rich-tracebacks = "^1.2.1"
uvicorn = "^0.20.0"

[tool.poetry.group.docs.dependencies]
cairosvg = "^2.7.0"
mkdocs-git-committers-plugin-2 = "^1.1.1"
pillow = "^9.4.0"
poethepoet = "^0.19.0"
mkdocs-material = { git = "https://github.com/squidfunk/mkdocs-material-insiders" }

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"

[tool.poe.tasks]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
