name: Deploy

on:
  push:
    branches:
      - vercel

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    environment: main
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'alter-negro[bot]' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Origin Branch
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: origin

      - name: Get Origin Branch (cont.)
        run: echo "ORIGIN=$(cat origin.txt)" >> $GITHUB_ENV

      - name: Restore Files
        run: git restore --source ${{ env.ORIGIN }} .poetry-version pyproject.toml poetry.lock vercel.json api

      - name: Install Poetry
        run: pipx install poetry==$(cat .poetry-version)

      - name: Export requirements.txt
        run: poetry export -o api/requirements.txt

      - name: Deploy to Vercel
        run: npx vercel --yes --token ${{ secrets.VERCEL_TOKEN }} ${{ env.ORIGIN == 'origin/main' && '--prod' || '' }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
