on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Freeze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.15

      - name: Install Poetry
        run: pipx install poetry==1.4.1

      - name: Install Dependencies
        run: poetry install --only docs

      - name: Get Major Version
        id: version
        run: echo "version=$(poetry version | cut -d ' ' -f 2 | cut -d '.' -f 1).0 >> $GITHUB_OUTPUT

      - name: Freeze
        run: mike deploy ${{ steps.version.outputs.version }} --branch staging --push
